export default [
  { figure:'Marc Jacobs', mark:'Freeman, Hadley (2007). "The geek of chic" TheAge.com.au (accessed 20070419)'                                                                          , quote:'It\'s the things that aren\'t accepted as conventionally beautiful that I find more attractive.'                                                                                                                                                                                                                                                                                                              }, 
  { figure:'Marc Jacobs', mark:'Freeman, Hadley (2007). "The geek of chic" TheAge.com.au (accessed 20070419)'                                                                          , quote:'I love the gym, but I still want to look a bit awkward at it. I don\'t want to look too on top of it, you know?'                                                                                                                                                                                                                                                                                              }, 
  { figure:'Marc Jacobs', mark:'Larocca, Amy (2005). "Marc Jacobs\' Paradoxial Triumph" NYMag.com (accessed 20070419)'                                                                 , quote:'Awkwardness gives me great comfort.'                                                                                                                                                                                                                                                                                                                                                                          }, 
  { figure:'Marc Jacobs', mark:'Larocca, Amy (2005). "Marc Jacobs\' Paradoxial Triumph" NYMag.com (accessed 20070419)'                                                                 , quote:'...People that don’t have any interest in the psychology of nuance, who need everything to be in their face, who don’t want to analyze... those aren’t the people I romanticize about dressing.'                                                                                                                                                                                                              }, 
  { figure:'Marc Jacobs', mark:'Clark, Mary (2001). "Index Magazine interview" indexmagazine.com (accessed 20070419)'                                                                  , quote:'I\'d like to believe that the women who wear my clothes are not dressing for other people, that they\'re wearing what they like and what suits them. It\'s not a status thing.'                                                                                                                                                                                                                               }, 
  { figure:'Marc Jacobs', mark:'Jonkers, Gert (2003). "Friendly homosexual fashion designer likes dogs but finds fashionable men terribly unsexy" buttmagazine.com (accessed 20070419)', quote:'I don’t believe in fashion dictatorship, and I find that anybody who follows the dictates of fashion is a bit lost. I’m excited by style, not so much by fashion.'                                                                                                                                                                                                                                            }, 
  { figure:'Marc Jacobs', mark:'Jonkers, Gert (2003). "Friendly homosexual fashion designer likes dogs but finds fashionable men terribly unsexy" buttmagazine.com (accessed 20070419)', quote:'Clothes to me aren’t sexy. Like, a dress isn’t sexy. Maybe the girl who wears it is sexy.'                                                                                                                                                                                                                                                                                                                    }, 
  { figure:'Marc Jacobs', mark:'Jonkers, Gert (2003). "Friendly homosexual fashion designer likes dogs but finds fashionable men terribly unsexy" buttmagazine.com (accessed 20070419)', quote:'It’s almost the not-knowing that’s sexy. When the look is too contrived... Trying to assimilate a look to be sexy to me is pretty transparent in the first place. So... somebody who just kind of stumbles into a sexy look... who’s not been thinking about fashion at all...'                                                                                                                               }, 
  { figure:'Marc Jacobs', mark:'Larocca, Amy (2005). "Marc Jacobs\' Paradoxial Triumph" NYMag.com (accessed 20070419)'                                                                 , quote:'We always say, ‘Gisele’s so hot, how do we break her down?\''                                                                                                                                                                                                                                                                                                                                                 }, 
  { figure:'Marc Jacobs', mark:'Larocca, Amy (2005). "Marc Jacobs\' Paradoxial Triumph" NYMag.com (accessed 20070419)'                                                                 , quote:'...Everybody likes sex. The world would be a better place if people just engaged in sex and didn’t worry about it. But what I prefer is that even if someone feels hedonistic, they don’t look it. Curiosity about sex is much more interesting to me than domination. Like, Britney and Paris and Pamela might be someone’s definition of sexy, but they’re not mine. My clothes are not hot. Never. Never.' }, 
]