export default [
  {
    figure: 'J. Bradford DeLong',
    mark: 'Ch6. "America’s Peacetime Inflation: The 1970s" in Reducing Inflation: Motivation and Strategy (1997) edited by Christina D. Romer and David H. Romer',
    quote: 'Economists’ instincts are that uncertainty about current prices, future prices, and the real meaning of nominal trade-offs between the present and the future; distortions introduced by the failure of government finance to be inflation-neutral; windfall redistributions; and the focusing of attention not on preferences, factors of production, and technologies but on predicting the future evolution of nominal magnitudes must degrade the functioning of the price system and reduce the effectiveness of the market economy at providing consumer utility. The cumulative jump in the price level as a result of the inflation of the 1970s may have been very expensive to the United States in terms of the associated reduction in human welfare.'
  },
  {
    figure: 'J. Bradford DeLong',
    mark: '"Should We Still Support Untrammelled International Capital Mobility? Or are Capital Controls Less Evil than We Once Believed?", The Economists\' Voice (2004)',
    quote: 'Fifteen years ago, I found it easy to be in favor of international capital mobility -- the free flow of investment financing from one country to another. Then it was easy to preach for an end to all systems of controls on capital that hindered this flow. Now it is harder.'
  },
  {
    figure: 'J. Bradford DeLong',
    mark: '"Understanding Karl Marx" (20090420)',
    quote: 'In my view, Marx has trapped himself. He has been primed to expect a deeper layer of real reality underneath mere appearances. And he has chosen the wrong model of the underlying real reality--the labor theory of value, which is simply not a very good model of the averages around which prices fluctuate. Socially-necessary labor power usually serves as an upper bound to value--if something sells for more, then a lot of people are going to start making more of them, and the prices at which it trades are going to fall. But lots of things sell for much less than the prices corresponding to their socially-necessary labor power lots of the time. And so Marx vanishes into the swamp which is the attempt to reconcile the labor theory of value with economic reality, and never comes out.'
  },
  {
    figure: 'J. Bradford DeLong',
    mark: 'Making Sense of Friedrich A. von Hayek: Focus/The Honest Broker for the Week of 20140809 (2014)',
    quote: 'Hayek says that the problem with classical liberalism was that it was not pure enough. The government needed to restrict itself to establishing the rule of law and to using antitrust to break up monopolies. It was the overreach of the government beyond those limits, via central banking and social democracy, that caused all the trouble. A democratic government needs to limit itself to rule of law and antitrust–and perhaps soup kitchens and shelters. And what if democracy turns out not to produce a government that limits itself to those activities? Then, Hayek says, so much the worse for democracy. A Pinochet is then called for to, in a Lykourgan moment, minimalize the state. After social democracy has been leveled and the rubble cleared away, then–perhaps–a limited range of issues can be discussed and debated by a–limited–restored democracy, with some kind of group of right-wing army officers descended from latifundistas Council of Guardians in the background to ensure that property remains sacred and protected, and the government small enough to fit in a bathtub. […] Hayek was formed in Austria. From his perspective the property and enterprise respecting Imperial Habsburg government of Franz Josef eager to make no waves, to hold what it has, and to keep the lid off the pressure cooker appears not unattractive. This is especially so when you contrasted would be really existing authoritarian alternatives: anti-Semitic populist demagogue mayors of Vienna; nationalist Serbian or Croatian politicians interested in maintaining popular legitimacy by waging class war or ethnic war; separatists who seek independence and then one man, one vote, one time. An “authoritarian” after the manner of Franz Josef looks quite attractive in this context–and if you convince yourself but they are as dedicated to small government neoliberalism as you are, and that the Lykourgan moment of the form will be followed by soft rule and popular assent, so much the better. And if the popular assent is not forthcoming? Then Hayek can blame the socialists, and say it is their fault for not understanding how good a deal they are offered.'
  },
  {
    figure: 'J. Bradford DeLong',
    mark: 'Making Sense of Friedrich A. von Hayek: Focus/The Honest Broker for the Week of 20140809 (2014)',
    quote: 'The Good Economist Hayek is the thinker who has mind-blowing insights into just why the competitive market system is such a marvelous societal device for coordinating our by now 7.\n2 billion-wide global division of labor. Few other economists imagined that Lenin’s centrally-planned economy behind the Iron Curtain was doomed to settle at a level of productivity 1/5 that of the capitalist industrial market economies outside. Hayek did so imagine. And Hayek had dazzling insights as to why. Explaining the thought of this Hayek requires not sociology or history of thought but rather appreciation, admiration, and respect for pure genius.\nThe Bad Economist Hayek is the thinker who was certain that Keynes had to be wrong, and that the mass unemployment of the Great Depression had to have in some mysterious way been the fault of some excessively-profligate government entity (or perhaps of those people excessively clever with money–fractional-reserve bankers, and those who claim not the natural increase of flocks but rather the interest on barren gold). Why Hayek could not see with everybody else–including Milton Friedman–that the Great Depression proved that Say’s Law was false in theory, and that aggregate demand needed to be properly and delicately managed in order to make Say’s Law true in practice is largely a mystery. Nearly everyone else did: the Lionel Robbinses and the Arthur Burnses quickly marked their beliefs to market after the Great Depression and figured out how to translate what they thought into acceptable post-World War II Keynesian language. Hayek never did.\nMy hypothesis is that the explanation is theology: For Hayek, the market could never fail. For Hayek, the market could only be failed. And the only way it could be failed was if its apostles were not pure enough.'
  },
]