export default [
  {
    figure: 'James Tobin',
    mark: '1950s. Tobin, James. "Liquidity preference as behavior towards risk." The review of economic studies (1958): 65-86.',
    quote: 'A forthcoming book by Harry Markowitz, Techniques of Portfolio Selection, will treat the general problem of finding dominant sets and computing the corresponding opportunity locus, for sets of securities all of which involve risk. Markowitz\'s main interest is prescription of rules of rational behaviour for investors; the main concern of this paper is the implications for economic theory, mainly comparative statics, that can be derived from assuming that investors do in fact follow such rules.'
  },
  {
    figure: 'James Tobin',
    mark: '1950s. Tobin, James. "Estimation of relationships for limited dependent variables." Econometrica: journal of the Econometric Society (1958): 24-36.',
    quote: 'In economic surveys of households, many variables have the following characteristics: The variable has a lower, or upper, limit and takes on the limiting value for a substantial number of respondents. For the remaining respondents, the variable takes on a For the remaining respondents, the variable takes on a wide range of values above, or below, the limit.'
  },
  {
    figure: 'James Tobin',
    mark: '1960s. "A general equilibrium approach to monetary theory" (1969). p21 as cited in: Sılvio Rendon, "Non-Tobin’s q in Tests for Financial Constraints," 2009',
    quote: 'The rate of investment – the speed at which investors wish to increase the capital stock – should be related, if to anything, to q, the value of capital relative to its replacement cost.'
  },
  {
    figure: 'James Tobin',
    mark: '1960s. "A general equilibrium approach to monetary theory" (1969). p29 As cited in: William Pool. Brookings Papers on Economic Activity, 2, (1976), p292',
    quote: 'According to [the general equilibrium approach to monetary theory], the principal way in which financial policies and events affect aggregate demand is by changing the valuations of physical assets relative to their replacement costs.'
  },
  {
    figure: 'James Tobin',
    mark: '1960s. "A general equilibrium approach to monetary theory" (1969). p29 as cited in: Andrés, Javier, J. David López-Salido, and Edward Nelson. "Tobin\'s imperfect asset substitution in optimizing general equilibrium." Journal of Money, Credit and Banking (2004): 665-690.',
    quote: 'There is no reason to think that the impact [of monetary policy] will be captured in any single [variable]... , whether it is a monetary stock or a market interest rate.'
  },
  {
    figure: 'James Tobin',
    mark: '1970s. Nordhaus, William D., and James Tobin. "Is growth obsolete?." Economic Research: Retrospect and Prospect Vol5. Economic Growth. Nber, 1972. 1-80.',
    quote: 'A long decade ago economic growth was the reigning fashion of political economy. It was simultaneously the hottest subject of economic theory and research, a slogan eagerly claimed by politicians of all stripes, and a serious objective of the policies of governments. The climate of opinion has changed dramatically. Disillusioned critics indict both economic science and economic policy for blind obeisance to aggregate material "progress," and for neglect of its costly side effects. Growth, it is charged, distorts national priorities, worsens the distribution of income, and irreparably damages the environment. Paul Erlich speaks for a multitude when he says, "We must acquire a life style which has as its goal maximum freedom and happiness for the individual, not a maximum Gross National Product."'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. James Tobin, in Conversations with Economists (1983) by Arjo Klamer',
    quote: 'Economics has always flourished and acquired energy from controversies generated by practical policy questions of the day. That was true in the times of Smith, and Ricardo, and Keynes, and it is true today. These periods of division and revolution and counterrevolution are generally followed by periods of synthesis and consolidation from which the science emerges stronger. i am optimistic that this will happen again, and that the best of the insights of the new clasicals will be absorbed in a mainstream, in which the essential insights of Keynesian economists also survive.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. James Tobin, "Keynes\' Policies in Theory and Practice", Challenge (1983).',
    quote: 'Monetarism—both of the older Friedman version stressing adherence to money stock targets and of the newer rational expectations variety—has been badly discredited. The stage has been set for recovery in the popularity of Keynesian diagnoses and remedies. I do not mean to imply, of course, that there is some Keynesian truth, vintage 1936 or 1961, to which economists and policymakers will or should now return, ignoring the lessons of economic events and of developments in economics itself over these last turbulent fifteen years. I do mean that in the new intellectual synthesis which I hope and expect will emerge to replace the divisive controversies and chaotic debates on macroeconomic policies, Keynesian ideas will have a prominent place.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. James Tobin, "Keynes\' Policies in Theory and Practice", Challenge (1983).',
    quote: 'Keynesian economics at a minimum provides a license for welfare state measures and other government efforts towards redistribution of wealth. The license is the faith that macroeconomic stabilization and prosperity are compatible with a wide range of social policies, that modern capitalism and democracy are robust enough to prosper and progress while being humane and equitable. That faith conflicts with the visions of extreme Right and Left, which agree that extremes of wealth and poverty, of security and insecurity, are indispensable to the functioning of capitalism. Keynesian policies helped to confound those dismal prophecies in the past; I think they will do so again.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. James Tobin, "A Revolution Remembered", Challenge (1988).',
    quote: 'Keynesian economics was, in the context of those times, essentially conservative. The message was that capitalism was not doomed; its major failing, chronic large-scale unemployment, could be remedied fairly easily, by intelligent use of the fiscal and monetary instruments governments already had at their disposal. This message was not welcome news to Marxists committed to the view that the system was no longer structurally capable of prosperity and progress.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. "James Tobin - Biographical" (1981)',
    quote: 'I studied economics and made it my career for two reasons. The subject was and is intellectually fascinating and challenging, particularly to someone with taste and talent for theoretical reasoning and quantitative analysis. At the same time it offered the hope, as it still does, that improved understanding could better the lot of mankind.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. "James Tobin - Biographical" (1981)',
    quote: 'For me, growing up in the 1930s, the two motivations powerfully reinforced each other. The miserable failures of capitalist economies in the Great Depression were root causes of worldwide social and political disasters. The crisis triggered a fertile period of scientific ferment and revolution in economic theory.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. "Money and Finance in the Macro-Economic Process" (1982). p12',
    quote: 'The historic terrain of macro-economic theory is the explanation of the levels and fluctuations of overall economic activity. Macro-economists have been especially interested in the effects of alternative fiscal, financial, and monetary policies.'
  },
  {
    figure: 'James Tobin',
    mark: '1980s. "Money and Finance in the Macro-Economic Process" (1982). p12',
    quote: 'With the publication of J. M. Keynes’s General Theory in 1936 and the mathematical formalizations of his theory by J. R. Hicks (1937) and others, the language of macro-economic theory became systems of simultaneous equations. These are general equilibrium systems of interdependence in the sense that the relationships describe an entire national economy, not just a particular industry or sector. The systems are usually not completely closed; they depend on exogenous parameters including instruments controlled by policy-makers. Seeking definite relationships of economic outcomes to policies and other exogenous variables, qualitative and quantitative, these models sacrifice detail and generality, limiting the number of variables and equations by aggregations over agents, commodities, assets, and time.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Price Flexibility and Output Stability: An Old Keynesian View" (1993)',
    quote: 'I had, to be sure, been drawn into economics when the General Theory was an exciting revelation for students hungry for explanation and remedy of the Great Depression. At the same time, I was uncomfortable with several aspects of Keynes’ theory, and I sought to improve what would now be called the microfoundations of his macroeconomic relations.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Price Flexibility and Output Stability: An Old Keynesian View" (1993)',
    quote: 'I shall argue that Keynesian macroeconomics neither asserts nor requires nominal wage and/or price rigidity. It does assert and require that markets not be instantaneously and continuously cleared by prices.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Price Flexibility and Output Stability: An Old Keynesian View" (1993)',
    quote: 'Ball, Mankiw, Romer and others style themselves as New Keynesians. Their program is to develop improved microeconomic foundations for imperfectly flexible prices. In the process, they hope to illuminate the paradox that individually rational or near-rational behavior can result in significant collective market failures. These are certainly laudable objectives. In the end, I suspect, the program will not change the essential substance of Keynesian macroeconomics. But it will make Keynes more palatable to theorists.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Price Flexibility and Output Stability: An Old Keynesian View" (1993)',
    quote: 'Keynes did not challenge the efficacy of price adjustment mechanisms in clearing particular markets in the Marshallian partial equilibrium theory on which he had been reared. He did challenge the mindless application of those mechanisms to economy-wide markets. Founding what came to be known as macroeconomics, he was modeling a whole economy as a closed system. He knew he could not use the Marshallian assumption that the clearing of one market could be safely described on the assumption that the rest of the economy was unaffected.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Reflections on Japanese Political Economy" (1999)',
    quote: 'I probably always say the same things; I hope people don\'t remember. One of the same things I say is that Japanese macroeconomic policy is perversely and inexcusably incompetent, and I surely would say that again. It\'s true-as Paul Krugman, a fellow participant in this program, has been saying and as I have said here in previous years-that Japan has reinvented the Keynesian liquidity trap. It can now reappear in classrooms where it had been long ignored or at best barely mentioned as a curiosum of the Great Depression.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Reflections on Japanese Political Economy" (1999)',
    quote: 'The central message is still that, as Keynes argued, fiscal policy is the answer to liquidity traps, financial or political. The arguments against fiscal policy in Japan, so far as I understand them are intellectually fallacious; they would receive failing grades in an undergraduate macro exam.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Reflections on Japanese Political Economy" (1999)',
    quote: 'The important Keynesian insight is that a high propensity to save will not generate high national saving unless it goes into investment, into accumulation of real capital. The "paradox of thrift" makes this point in an extreme way. In certain circumstances, when there is no demand for investment around, the economy can be no better off, or even worse off, if a thrifty public cuts consumption.'
  },
  {
    figure: 'James Tobin',
    mark: '1990s. "Reflections on Japanese Political Economy" (1999)',
    quote: 'I suspect that many of the world\'s financial lords are somewhat embarrassed to tell Japan repeatedly at G-7 meetings and elsewhere to adopt a Keynesian solution. Within Europe, central banks and governments think Keynesian theories and policies are absolutely wrong. Despite the remarkable success of pragmatic policies in the United States, true believers in the Invisible Hand reject Keynesian diagnoses and prescriptions. Many observers of Japan have found it intellectually comforting to blame the slump on the plight of the banks, flooded with bad loans dated from the land and equity bubbles and their collapse. They hope that a governmentmanaged and -subsidized rectification of bank balance sheets will trigger overall economic recovery. I think this is a false hope. The bank problem is only a small part of the macroeconomic disaster. It has to be resolved, of course, but resolution that is no substitute for the needed fiscal and monetary stimuli.'
  },
]