export default [
  { figure:'Eric Schmidt', mark:'Charlie Rose interview, 20050603, quoted in An Old Eric Schmidt Interview Reveals Google’s End-Game For Search And Competition by TechCrunch (20130104).', quote:'When you use Google, do you get more than one answer? Of course you do. Well, that’s a bug. We have more bugs per second in the world. We should be able to give you the right answer just once. We should know what you meant. You should look for information. We should get it exactly right and we should give it to you in your language and we should never be wrong. That’s our challenge.' }, 
  { figure:'Eric Schmidt', mark:'CNBC interview, 20091203, quoted in Google CEO on Privacy (20100318).'                                                                                   , quote:'If you have something that you don’t want anyone to know, maybe you shouldn’t be doing it in the first place.'                                                                                                                                                                                                                                                                                     }, 
  { figure:'Eric Schmidt', mark:'The Wall Street Journal (20100814).'                                                                                                                     , quote:'I actually think most people don\'t want Google to answer their questions. They want Google to tell them what they should be doing next.'                                                                                                                                                                                                                                                          }, 
  { figure:'Eric Schmidt', mark:'Google\'s Eric Schmidt Talks to Charlie Rose in Businessweek (20100923).'                                                                                , quote:'Ultimately, in the Internet, openness has always won. I cannot imagine that the current competitive environment would reverse that.'                                                                                                                                                                                                                                                               }, 
  { figure:'Eric Schmidt', mark:'With \'Millions\' Of Users & Growing, Google+ Set To Power All Google Products in Search Engine Land (20110709).'                                        , quote:'The current inclination of the company is to invest heavily ... we test stuff and, when it works, we put a lot more emphasis on it. So, Google+ — all the signs are very positive, so now the whole company is ramping up on top of it.'                                                                                                                                                           }, 
  { figure:'Eric Schmidt', mark:'Google\'s Schmidt: Android leads the iPhone in CNET (20111207).'                                                                                         , quote:'Ultimately, application vendors are driven by volume, and volume is favored by the open approach Google is taking. There are so many manufacturers working so hard to distribute Android phones globally that whether you like [Android 4.0] or not … you will want to develop for that platform, and perhaps even first.'                                                                         }, 
  { figure:'Eric Schmidt', mark:'Eric Schmidt: Google TV on \'majority\' of new TVs by summer 2012 in The Verge (20111207).'                                                              , quote:'By the summer of 2012, the majority of the televisions you see in stores will have Google TV embedded.'                                                                                                                                                                                                                                                                                            }, 
  { figure:'Eric Schmidt', mark:'Eric Schmidt: \'Playing catch-up with the competition will never help you create something new\' in MacDailyNews (20140828).'                            , quote:'Playing catch-up with the competition can only ever help you make incremental gains. It will never help you create something new.'                                                                                                                                                                                                                                                                 }, 
  { figure:'Eric Schmidt', mark:'Eric Schmidt says Google \'far more secure\' than Apple, denies allegations of harvesting data in AppleInsider (20141002).'                              , quote:'We have always been the leader in security and in encryption. Our systems are far more secure and encrypted than anyone else, including Apple. They\'re catching up, which is great.'                                                                                                                                                                                                              }, 
  { figure:'Eric Schmidt', mark:'\'They\'re just literally lying\': Google’s Eric Schmidt on cutting ties with conservative group in SFGate (20140922).'                                  , quote:'Everyone understands climate change is occurring and the people who oppose it are really hurting our children and our grandchildren and making the world a much worse place. And so we should not be aligned with such people — they\'re just, they\'re just literally lying.'                                                                                                                     }, 
]